"username" = "نام کاربری"
"password" = "رمز عبور"
"login" = "ورود"
"confirm" = "تائید"
"cancel" = "لغو"
"close" = "بستن"
"copy" = "کپی"
"copied" = "کپی شد"
"download" = "دانلود"
"remark" = "نام"
"enable" = "فعال"
"protocol" = "پروتکل"

"loading" = "در حال بارگذاری"
"second" = "ثانیه"
"minute" = "دقیقه"
"hour" = "ساعت"
"day" = "روز"
"check" = "بررسی"
"indefinitely" = "به طور نامحدود"
"unlimited" = "نامحدود"
"none" = "هیچ یک"
"qrCode" = "کیو آر کد"
"edit" = "ویرایش"
"delete" = "پاک کردن"
"reset" = "بازنشانی"
"copySuccess" = "با موفقیت کپی شد"
"sure" = "آغاز"
"encryption" = "رمزنگاری"
"transmission" = "انتقال"
"host" = "میزبان"
"path" = "مسیر"
"camouflage" = "استتار"
"turnOn" = "روشن"
"closure" = "پایان"
"domainName" = "نام دامنه"
"additional" = "افزوده"
"monitor" = "مانیتور"
"certificate" = "گواهی"
"fail" = "شکست"
"success" = "موفق"
"getVersion" = "دریافت نسخه"
"install" = "نصب"

[menu]
"dashboard" = "وضعیت سیستم"
"inbounds" = "ورودی ها"
"setting" = "تنظیمات پنل"
"logout" = "خروج"
"link" = "سایر"

[pages.login]
"title" = "ورود"
"loginAgain" = "محدودیت زمانی برای ورود به سیستم به پایان رسیده است، لطفا دوباره وارد شوید"

[pages.login.toasts]
"invalidFormData" = "قالب داده ورودی نامعتبر است"
"emptyUsername" = "لطفا نام کاربری را وارد کنید"
"emptyPassword" = "لطفا رمز را وارد کنید"
"wrongUsernameOrPassword" = "نام کاربری یا رمز نامعتبر است"
"successLogin" = "ورود موفق"


[pages.index]
"title" = "وضعیت سیستم"
"memory" = "حافظه"
"hard" = "محل ذخیره"
"xrayStatus" = "وضعیت ایکس ری"
"xraySwitch" = "تعویض نسخه"
"xraySwitchClick" = "بر روی نسخه ای که میخواهید تعویض کنید کلیک کنید."
"xraySwitchClickDesk" = "لطفاً با دقت انتخاب کنید، نسخه‌های قدیمی‌تر ممکن است تنظیمات ناسازگاری داشته باشند."
"operationHours" = "ساعات عملیات"
"operationHoursDesc" = "زمان اجرای سیستم از زمان راه اندازی آن"
"systemLoad" = "بار سیستم"
"connectionCount" = "شمار اتصال ها"
"connectionCountDesc" = "تعداد کل اتصالات برای همه کارت های شبکه"
"upSpeed" = "سرعت کل آپلود برای همه کارت های شبکه"
"downSpeed" = "سرعت کل دانلود برای همه کارت های شبکه"
"totalSent" = "کل ترافیک آپلود همه کارت های شبکه از زمان راه اندازی سیستم"
"totalReceive" = "کل ترافیک دانلود همه کارت های شبکه از زمان راه اندازی سیستم"
"xraySwitchVersionDialog" = "تغییر نسخه ایکس ری"
"xraySwitchVersionDialogDesc" = "نسخه ایکس ری به کدام تغییر داده شود"
"dontRefreshh" = "در حال نصب. لطفا صفحه را بازنشانی نکنید."


[pages.inbounds]
"title" = "ورودی ها"
"totalDownUp" = "کل دانلود ها / آپلود ها"
"totalUsage" = "استفاده کل"
"inboundCount" = "تعداد ورودی ها"
"operate" = "راه اندازی"
"enable" = "فعال"
"remark" = "نام"
"protocol" = "پروتکل"
"port" = "پورت"
"traffic" = "ترافیک"
"details" = "جزئیات"
"transportConfig" = "پیکربندی حمل و نقل"
"expireDate" = "تاریخ انقضاء"
"resetTraffic" = "بازنشانی ترافیک"
"addInbound" = "اضافه کردن ورودی"
"addTo" = "اضافه کردن به"
"revise" = "دریافت"
"modifyInbound" = "اصلاح ورودی"
"deleteInbound" = "حذف ورودی"
"deleteInboundContent" = "آیا مطمئن هستید که می خواهید ورودی را پاک کنید؟"
"resetTrafficContent" = "آیا مطمئن هستید که می خواهید ترافیک را بازنشانی کنید؟"
"copyLink" = "کپی کردن آدرس"
"address" = "آدرس"
"network" = "شبکه"
"destinationPort" = "پورت مقصد"
"targetAddress" = "آدرس هدف"
"disableInsecureEncryption" = "غیر فعال سازی رمزنگاری نا امن"
"monitorDesc" = "برای پیش فرض خالی بگذارید"
"meansNoLimit" = "به معنی عدم محدودیت"
"totalFlow" = "جریان کل"
"leaveBlankToNeverExpire" = "خالی بگذارید تا هرگز منقضی نشود"
"noRecommendKeepDefault" = "هیچ الزام خاصی برای حفظ پیش فرض وجود ندارد"
"certificatePath" = "مسیر فایل گواهی"
"certificateContent" = "محتوای گواهی"
"publicKeyPath" = "مسیر کلید عمومی"
"publicKeyContent" = "محتوای کلید عمومی"
"keyPath" = "مسیر کلید"
"keyContent" = "محتوای کلید"
"path" = "مسیر"
"requestVersion" = "درخواست نسخه"
"requestMethod" = "درخواست روش"
"requestPath" = "درخواست مسیر"
"requestHeader" = "درخواست هدر"
"name" = "نام"
"value" = "مقدار"
"responseVersion" = "پاسخ نسخه"
"responseStatus" = "پاسخ وضعیت"
"responseReason" = "پاسخ دلیل"
"responseHeader" = "پاسخ هدر"
"camouflage" = "استتار"
"encryption" = "رمزنگاری"
"username" = "نام کاربری"
"password" = "رمز عبور"


[pages.inbounds.toasts]
"obtain" = "گرفتن"

[pages.inbounds.stream.general]
"requestHeader" = "درخواست هدر"
"name" = "نام"
"value" = "مقدار"

[pages.inbounds.stream.tcp]
"requestVersion" = "درخواست نسخه"
"requestMethod" = "درخواست روش"
"requestPath" = "درخواست مسیر"
"responseVersion" = "پاسخ نسخه"
"responseStatus" = "پاسخ وضعیت"
"responseStatusDescription" = "پاسخ توضیحات وضعیت"
"responseHeader" = "پاسخ هدر"

[pages.inbounds.stream.quic]
"encryption" = "رمزنگاری"

[pages.setting]
"title" = "تنظیمات"
"save" = "ذخیره"
"restartPanel" = "راه اندازی مجدد پنل"
"restartPanelDesc" = "آیا مطمئن هستید که میخواهید پنل را دوباره راه اندازی کنید؟ روی اوکی کلیک کنید تا بعد از سه ثانیه مجدد راه اندازی شود. اگر پس از راه اندازی مجدد قادر به دسترسی به پنل نبودید، به سرور مراجعه کنید"
"panelConfig" = "پیکربندی پنل"
"userSetting" = "تنظیمات کاربر"
"xrayConfiguration" = "پیکربندی ایکس ری"
"TGReminder" = "تنظیمات مربوط به یادآور  تلگرام"
"otherSetting" = "تنظیمات دیگر"
"panelListeningIP" = "آی پی لیسنینگ پنل"
"panelListeningIPDesc" = "برای نظارت بر همه آی پی ها به طور پیش فرض خالی بگذارید. پنل را مجدد راه اندازی کنید تا اعمال شود."
"panelPort" = "پورت پنل"
"panelPortDesc" = "پنل را مجدد راه اندازی کنید تا اعمال شود."
"publicKeyPath" = "مسیر کلید عمومی پنل"
"publicKeyPathDesc" = "یک مسیر مطلق که با '/' شروع می شود را پر کنید، پنل را مجددا راه اندازی کنید تا اعمال شود"
"privateKeyPath" = "مسیر کلید خصوصی پنل"
"privateKeyPathDesc" = "یک مسیر مطلق که با '/' شروع می شود را پر کنید، پنل را مجددا راه اندازی کنید تا اعمال شود"
"panelUrlPath" = "مسیر آدرس اینترنتی روت پنل"
"panelUrlPathDesc" = "باید با '/' شروع شود و با '/' تمام شود، پنل را مجدداً راه اندازی کنید تا اعمال شود"
"oldUsername" = "نام کاربری فعلی"
"currentPassword" = "رمز ورود فعلی"
"newUsername" = "نام کاربری جدید"
"newPassword" = "رمز ورود جدید"
"xrayConfigTemplate" = "الگوی پیکربندی ایکس ری"
"xrayConfigTemplateDesc" = "فایل پیکربندی نهایی ایکس ری را بر اساس این الگو ایجاد کنید، پنل را مجدداً راه اندازی کنید تا اعمال شود"
"telegramBotEnable" = "فعال سازی بات تلگرام"
"telegramBotEnableDesc" = "پنل را راه اندازی مجدد کنید تا اعمال شود"
"telegramToken" = "توکن تلگرام"
"telegramTokenDesc" = "پنل را راه اندازی مجدد کنید تا اعمال شود"
"telegramChatId" = "چت آی دی تلگرام"
"telegramChatIdDesc" = "پنل را راه اندازی مجدد کنید تا اعمال شود"
"telegramNotifyTime" = "زمان اطلاع رسانی بات تلگرام"
"telegramNotifyTimeDesc" = "با استفاده از قالب زمان بندی کرون تب، پنل را مجددا راه اندازی کنید تا اعمال شود"
"timeZonee" = "منطقه زمانی"
"timeZoneDesc" = "کار برنامه ریزی شده مطابق با زمان در منطقه زمانی اجرا می شود و پان را مجدداً راه اندازی می کند تا اعمال شود"

[pages.setting.toasts]
"modifySetting" = "تغییر تنظیمات"
"getSetting" = "تنظیم"
"modifyUser" = "تغییر کاربر"
"originalUserPassIncorrect" = "نام کاربری اصلی یا رمز عبور اصلی نادرست است"
"userPassMustBeNotEmpty" = "نام کاربری جدید و رمز عبور جدید نمی توانند خالی باشند"

[api.inbound]
"removeInboundSuccessMessage" = "Removed inbound successfully"

[api.auth]
"unauthorizedMessage" = "You are unauthenticated"
