"username" = "Username"
"password" = "Password"
"login" = "Login"
"confirm" = "Confirm"
"cancel" = "Cancel"
"close" = "Close"
"copy" = "Copy"
"copied" = "Copied"
"download" = "Download"
"remark" = "Remark"
"enable" = "Enable"
"protocol" = "Protocol"

"loading" = "Loading..."
"second" = "Seconds"
"minute" = "Minutes"
"hour" = "Hours"
"day" = "Days"
"check" = "Check"
"indefinitely" = "Indefinitely"
"unlimited" = "Unlimited"
"none" = "None"
"qrCode" = "QR Code"
"edit" = "Edit"
"delete" = "Delete"
"reset" = "Reset"
"copySuccess" = "Copied successfully"
"sure" = "Sure"
"encryption" = "Encryption"
"transmission" = "Transmission"
"host" = "Host"
"path" = "Path"
"camouflage" = "Camouflage"
"turnOn" = "Turn ON"
"closure" = "Closure"
"domainName" = "Domain name"
"additional" = "Additional"
"monitor" = "Monitor"
"certificate" = "Certificat"
"fail" = "Faild"
"success" = "Succeed"
"getVersion" = "Get version"
"install" = "Install"

[menu]
"dashboard" = "System Status"
"inbounds" = "Inbounds"
"setting" = "Panel Settings"
"logout" = "Log Out"
"link" = "Other"

[pages.login]
"title" = "Login"
"loginAgain" = "The login session has expired, please log in again"

[pages.login.toasts]
"invalidFormData" = "Input Data Format Is Invalid"
"emptyUsername" = "Please Enter Username"
"emptyPassword" = "Please Enter Password"
"wrongUsernameOrPassword" = "Invalid username or password. Try again"
"successLogin" = "Login"


[pages.index]
"title" = "System Status"
"memory" = "Memory"
"hard" = "Hard Disk"
"xrayStatus" = "XRAY Status"
"xraySwitch" = "Switch Version"
"xraySwitchClick" = "Click on the version you want to switch"
"xraySwitchClickDesk" = "Please choose carefully. Older versions may have incompatible configurations. Default recommended"
"operationHours" = "Operation Hours"
"operationHoursDesc" = "The uptime of the system since it was started"
"systemLoad" = "System Load"
"connectionCount" = "Connections Count"
"connectionCountDesc" = "The total number of connections for all network cards"
"upSpeed" = "Total upload speed for all network cards"
"downSpeed" = "Total download speed for all network cards"
"totalSent" = "Total upload traffic of all network cards since system startup"
"totalReceive" = "Total download traffic of all network cards since system startup"
"xraySwitchVersionDialog" = "Switch XRAY version"
"xraySwitchVersionDialogDesc" = "Are you sure to switch the xray version to"
"dontRefreshh" = "Installation is in progress... Please do not refresh this page"


[pages.inbounds]
"title" = "Inbounds"
"totalDownUp" = "Total uploads/downloads"
"totalUsage" = "Total usage"
"inboundCount" = "Number of inbounds"
"operate" = "operate"
"enable" = "enable"
"remark" = "remark"
"protocol" = "protocol"
"port" = "port"
"traffic" = "traffic"
"details" = "details"
"transportConfig" = "Transport config"
"expireDate" = "Expiry date"
"resetTraffic" = "Reset traffic"
"addInbound" = "Add Inbound"
"addTo" = "Add To"
"revise" = "Revise"
"modifyInbound" = "Modify InBound"
"deleteInbound" = "Delete Inbound"
"deleteInboundContent" = "Are you sure you want to delete the inbound?"
"resetTrafficContent" = "Are you sure you want to reset the traffic?"
"copyLink" = "Copy Link"
"address" = "Address"
"network" = "Network"
"destinationPort" = "Destination port"
"targetAddress" = "Target address"
"disableInsecureEncryption" = "Disable insecure encryption"
"monitorDesc" = "Leave blank to listen all IPs"
"meansNoLimit" = "0 means no limit"
"totalFlow" = "Total Traffic"
"leaveBlankToNeverExpire" = "Leave blank to never expire"
"noRecommendKeepDefault" = "There are no special requirements to keep the default"
"certificatePath" = "Certificate file path"
"certificateContent" = "Certificate.crt file content"
"publicKeyPath" = "Certificate.crt file path"
"publicKeyContent" = "Public key content"
"keyPath" = "Private.key file path"
"keyContent" = "Private.Key content"
"path" = "Path"
"requestVersion" = "Request version"
"requestMethod" = "Request method"
"requestPath" = "Request path"
"requestHeader" = "Request header"
"name" = "Name"
"value" = "Value"
"responseVersion" = "Response version"
"responseStatus" = "Response status"
"responseReason" = "Response reason"
"responseHeader" = "Response header"
"camouflage" = "Camouflage"
"encryption" = "Encryption"
"username" = "Username"
"password" = "Password"


[pages.inbounds.toasts]
"obtain" = "Obtain"

[pages.inbounds.stream.general]
"requestHeader" = "request header"
"name" = "name"
"value" = "value"

[pages.inbounds.stream.tcp]
"requestVersion" = "request version"
"requestMethod" = "request method"
"requestPath" = "request path"
"responseVersion" = "response version"
"responseStatus" = "response status"
"responseStatusDescription" = "response status description"
"responseHeader" = "response header"

[pages.inbounds.stream.quic]
"encryption" = "encryption"

[pages.setting]
"title" = "Setting"
"save" = "Save"
"restartPanel" = "Restart Panel"
"restartPanelDesc" = "Are you sure you want to restart the panel? Click OK to restart. If you cannot access the panel after 3 seconds, Please go to the server to view the panel log information"
"panelConfig" = "Panel Configuration"
"userSetting" = "User Setting"
"xrayConfiguration" = "XRAY Configuration"
"TGReminder" = "TG Bot Related Settings"
"otherSetting" = "Other Setting"
"panelListeningIP" = "Panel listening IP"
"panelListeningIPDesc" = "Leave blank by default to monitor all IPs. Restart the panel to take effect"
"panelPort" = "Panel Port"
"panelPortDesc" = "Restart the panel to take effect"
"publicKeyPath" = "Panel certificate.crt file path"
"publicKeyPathDesc" = "Fill in an absolute path starting with '/'. Restart the panel to take effect"
"privateKeyPath" = "Panel private.key file path"
"privateKeyPathDesc" = "Fill in an absolute path starting with '/'. Restart the panel to take effect"
"panelUrlPath" = "Panel url root path"
"panelUrlPathDesc" = "Must start with '/' and end with '/'. Restart the panel to take effect"
"oldUsername" = "Current Username"
"currentPassword" = "Current Password"
"newUsername" = "New Username"
"newPassword" = "New Password"
"xrayConfigTemplate" = "XRAY Configuration Template"
"xrayConfigTemplateDesc" = "Generating the final XRAY configuration file based on this template. Restart the panel to take effect"
"telegramBotEnable" = "Enable Telegram bot"
"telegramBotEnableDesc" = "Restart the panel to take effect"
"telegramToken" = "Telegram Token"
"telegramTokenDesc" = "Restart the panel to take effect"
"telegramChatId" = "Telegram ChatId (Get from @getidsbot) "
"telegramChatIdDesc" = "Restart the panel to take effect"
"telegramNotifyTime" = "Telegram bot notification time"
"telegramNotifyTimeDesc" = "Using Crontab timing format. (Refer the REDME.md)  Restart the panel to take effect"
"timeZonee" = "Time Zone"
"timeZoneDesc" = "The scheduled tasks run according to this the time zone. Restarts the panel to take effect"

[pages.setting.toasts]
"modifySetting" = "Modify settings"
"getSetting" = "Get setting"
"modifyUser" = "Modify user"
"originalUserPassIncorrect" = "The current user name or original password is incorrect"
"userPassMustBeNotEmpty" = "New username and new password cannot be empty"
