"username" = "Nome do usuário"
"password" = "Senha"
"login" = "Entrar"
"confirm" = "Confirmar"
"cancel" = "Cancelar"
"close" = "Fechar"
"copy" = "Copiar"
"copied" = "Copiado"
"download" = "Baixar"
"remark" = "Observação"
"enable" = "Ativar"
"protocol" = "Protocolo"

"loading" = "Carregando..."
"second" = "Segundos"
"minute" = "Minutos"
"hour" = "Horas"
"day" = "Dias"
"check" = "Verificar"
"indefinitely" = "Indefinidamente"
"unlimited" = "Ilimitado"
"none" = "Nenhum"
"qrCode" = "Código QR"
"edit" = "Editar"
"delete" = "Deletar"
"reset" = "Resetar"
"copySuccess" = "Copiado com sucesso"
"sure" = "Tem certeza?"
"encryption" = "Criptografia"
"transmission" = "Transmissão"
"host" = "Host"
"path" = "Caminho"
"camouflage" = "Camuflagem"
"turnOn" = "Ligar"
"closure" = "Desligar"
"domainName" = "Nome do domínio"
"additional" = "Adicional"
"monitor" = "Monitor"
"certificate" = "Certificado"
"fail" = "Falha"
"success" = "Sucesso"
"getVersion" = "Obter versão"
"install" = "Instalar"

[menu]
"dashboard" = "Status do sistema"
"inbounds" = "Entradas"
"setting" = "Configurações do Painel"
"logout" = "Sair"
"link" = "Outros"

[pages.login]
"title" = "Entrar"
"loginAgain" = "A sessão de login expirou, por favor, faça login novamente"

[pages.login.toasts]
"invalidFormData" = "Dados inválidos"
"emptyUsername" = "Por favor, insira o nome do usuário"
"emptyPassword" = "Por favor, insira a senha"
"wrongUsernameOrPassword" = "Nome de usuário ou senha incorretos, por favor, tente novamente"
"successLogin" = "Login bem sucedido"


[pages.index]
"title" = "Status do sistema"
"memory" = "Memória"
"hard" = "Disco rígido"
"xrayStatus" = "Status do XRAY"
"xraySwitch" = "Versão do Switch"
"xraySwitchClick" = "Clique na versão que você deseja mudar"
"xraySwitchClickDesk" = "Escolha com cuidado. Versões mais antigas podem ter configurações incompatíveis. (Recomendado o padrão)"
"operationHours" = "Horas de operação"
"operationHoursDesc" = "O tempo de atividade do sistema desde que foi iniciado"
"systemLoad" = "Carga do sistema"
"connectionCount" = "Total de conexões"
"connectionCountDesc" = "O número total de conexões para todas as placas de rede"
"upSpeed" = "Velocidade total de upload para todas as placas de rede"
"downSpeed" = "Velocidade total de download para todas as placas de rede"
"totalSent" = "Tráfego total de upload de todas as placas de rede desde a inicialização do sistema"
"totalReceive" = "Tráfego total de download de todas as placas de rede desde a inicialização do sistema"
"xraySwitchVersionDialog" = "Alternar versão do XRAY"
"xraySwitchVersionDialogDesc" = "Tem certeza de mudar a versão xray para"
"dontRefreshh" = "A instalação está em andamento... Por favor, não atualize a página"


[pages.inbounds]
"title" = "Entradas"
"totalDownUp" = "Total de uploads/downloads"
"totalUsage" = "Uso total"
"inboundCount" = "Número de entradas"
"operate" = "Operar"
"enable" = "Habilitar"
"remark" = "Observação"
"protocol" = "Protocolo"
"port" = "Porta"
"traffic" = "Tráfego"
"details" = "Detalhes"
"transportConfig" = "Configuração de transporte"
"expireDate" = "Data de expiração"
"resetTraffic" = "Resetar tráfego"
"addInbound" = "Adicionar entrada"
"addTo" = "Adicionar para"
"revise" = "Editar"
"modifyInbound" = "Editar entrada"
"deleteInbound" = "Deletar entrada"
"deleteInboundContent" = "Tem certeza de que deseja excluir a entrada?"
"resetTrafficContent" = "Tem certeza de que deseja redefinir o tráfego?"
"copyLink" = "Copiar link"
"address" = "Endereço"
"network" = "Rede"
"destinationPort" = "Porta de destino"
"targetAddress" = "Endereço de destino"
"disableInsecureEncryption" = "Desativar criptografia insegura"
"monitorDesc" = "Deixe em branco para ouvir todos os IPs"
"meansNoLimit" = "0, significa sem limite"
"totalFlow" = "Tráfego total"
"leaveBlankToNeverExpire" = "Deixe em branco para nunca expirar"
"noRecommendKeepDefault" = "Não recomendado, mantenha o padrão"
"certificatePath" = "Caminho do arquivo de certificado"
"certificateContent" = "Conteúdo do certificado"
"publicKeyPath" = "Caminho da chave pública"
"publicKeyContent" = "Conteúdo da chave pública"
"keyPath" = "Caminho da chave privada"
"keyContent" = "Conteúdo da chave privada"
"path" = "Caminho"
"requestVersion" = "Versão solicitada"
"requestMethod" = "Método de solicitação"
"requestPath" = "Caminho da solicitação"
"requestHeader" = "Cabeçalho da solicitação"
"name" = "Nome"
"value" = "Valor"
"responseVersion" = "Versão de resposta"
"responseStatus" = "Status de resposta"
"responseReason" = "Razão da resposta"
"responseHeader" = "Cabeçalho de resposta"
"camouflage" = "Camuflagem"
"encryption" = "Criptografia"
"username" = "Nome de usuário"
"password" = "Senha"


[pages.inbounds.toasts]
"obtain" = "Obtain"

[pages.inbounds.stream.general]
"requestHeader" = "Cabeçalho da solicitação"
"name" = "Nome"
"value" = "Valor"

[pages.inbounds.stream.tcp]
"requestVersion" = "Versão solicitada"
"requestMethod" = "Método de solicitação"
"requestPath" = "Caminho da solicitação"
"responseVersion" = "Versão de resposta"
"responseStatus" = "Status de resposta"
"responseStatusDescription" = "Descrição do status de resposta"
"responseHeader" = "Cabeçalho de resposta"

[pages.inbounds.stream.quic]
"encryption" = "Criptografia"

[pages.setting]
"title" = "Configurações"
"save" = "Salvar"
"restartPanel" = "Reiniciar painel"
"restartPanelDesc" = "Tem certeza de que deseja reiniciar o painel? Clique em OK para reiniciar. Se você não conseguir acessar o painel após 3 segundos, vá para o servidor para visualizar as informações de registro do painel"
"panelConfig" = "Configuração do painel"
"userSetting" = "Configuração do usuário"
"xrayConfiguration" = "Configuração do XRAY"
"TGReminder" = "Configurações relacionadas ao Telegram Bot"
"otherSetting" = "Outras configurações"
"panelListeningIP" = "IP de escuta do painel"
"panelListeningIPDesc" = "Deixe em branco por padrão para monitorar todos os IPs. Reinicie o painel para entrar em vigor"
"panelPort" = "Porta do painel"
"panelPortDesc" = "Reinicie o painel para entrar em vigor"
"publicKeyPath" = "Caminho do arquivo certificate.crt do painel"
"publicKeyPathDesc" = "Preencha o caminho absoluto começando com '/'. Reinicie o painel para entrar em vigor"
"privateKeyPath" = "Caminho do arquivo private.key do painel"
"privateKeyPathDesc" = "Preencha o caminho absoluto começando com '/'. Reinicie o painel para entrar em vigor"
"panelUrlPath" = "Caminho da URL do painel"
"panelUrlPathDesc" = "Deve começar com '/' e terminar com '/'. Reinicie o painel para entrar em vigor"
"oldUsername" = "Nome de usuário atual"
"currentPassword" = "Senha atual"
"newUsername" = "Novo nome de usuário"
"newPassword" = "Nova senha"
"xrayConfigTemplate" = "Modelo de configuração do XRAY"
"xrayConfigTemplateDesc" = "Gerando o arquivo de configuração XRAY final com base neste modelo. Reinicie o painel para entrar em vigor"
"telegramBotEnable" = "Habilitar bot do Telegram"
"telegramBotEnableDesc" = "Reinicie o painel para entrar em vigor"
"telegramToken" = "Token do bot do Telegram"
"telegramTokenDesc" = "Reinicie o painel para entrar em vigor"
"telegramChatId" = "Telegram ChatId (Obtenha seu id em @getidsbot) "
"telegramChatIdDesc" = "Reinicie o painel para entrar em vigor"
"telegramNotifyTime" = "Tempo de notificação do bot do Telegram"
"telegramNotifyTimeDesc" = "Usando o formato de cronometragem Crontab. (Consulte o REDME.md). Reinicie o painel para entrar em vigor"
"timeZonee" = "Fuso horário"
"timeZoneDesc" = "As tarefas agendadas são executadas de acordo com esse fuso horário. Reinicia o painel para entrar em vigor"

[pages.setting.toasts]
"modifySetting" = "Modificar configurações"
"getSetting" = "Obter configurações"
"modifyUser" = "Modificar usuário"
"originalUserPassIncorrect" = "O nome de usuário atual ou a senha original está incorreto"
"userPassMustBeNotEmpty" = "Novo nome de usuário e nova senha não podem estar vazios"